# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=10)),
                ('location_exp', models.CharField(blank=True, max_length=25, null=True)),
                ('patient_category_code', models.CharField(blank=True, max_length=2, null=True)),
                ('unit_location_group_exp', models.CharField(blank=True, max_length=26, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
