# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceno', models.CharField(blank=True, db_column='AttendanceNo', max_length=50, null=True)),
                ('patientid', models.CharField(blank=True, db_column='PatientID', max_length=50, null=True)),
                ('age', models.CharField(blank=True, db_column='Age', max_length=10, null=True)),
                ('episodedate', models.CharField(blank=True, db_column='EpisodeDate', max_length=27, null=True)),
                ('dischargetype', models.CharField(blank=True, db_column='DischargeType', max_length=50, null=True)),
                ('arrivaltype', models.CharField(blank=True, db_column='ArrivalType', max_length=10, null=True)),
                ('plannedorunplanned', models.CharField(blank=True, db_column='Plannedorunplanned', max_length=10, null=True)),
                ('patientgroup', models.CharField(blank=True, db_column='PatientGroup', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('timeinae', models.CharField(blank=True, max_length=10, null=True)),
                ('hospitalsite', models.CharField(blank=True, db_column='HospitalSite', max_length=10, null=True)),
                ('consultantcode', models.CharField(blank=True, max_length=10, null=True)),
                ('attendingclinician', models.CharField(blank=True, db_column='AttendingClinician', max_length=10, null=True)),
                ('consultingclinician1', models.CharField(blank=True, db_column='ConsultingClinician1', max_length=10, null=True)),
                ('consultingclinician2', models.CharField(blank=True, db_column='ConsultingClinician2', max_length=10, null=True)),
                ('triagenurse', models.CharField(blank=True, db_column='TriageNurse', max_length=10, null=True)),
                ('presentingcomplaint', models.CharField(blank=True, db_column='PresentingComplaint', max_length=255, null=True)),
                ('diagnosisdescription1', models.CharField(blank=True, db_column='DiagnosisDescription1', max_length=255, null=True)),
                ('diagnosiscode1', models.CharField(blank=True, db_column='DiagnosisCode1', max_length=10, null=True)),
                ('diagnosisdescription2', models.CharField(blank=True, db_column='DiagnosisDescription2', max_length=255, null=True)),
                ('diagnosiscode2', models.CharField(blank=True, db_column='DiagnosisCode2', max_length=10, null=True)),
                ('diagnosisdescription3', models.CharField(blank=True, db_column='DiagnosisDescription3', max_length=255, null=True)),
                ('diagnosiscode3', models.CharField(blank=True, db_column='DiagnosisCode3', max_length=10, null=True)),
                ('diagnosisdescription4', models.CharField(blank=True, db_column='DiagnosisDescription4', max_length=255, null=True)),
                ('diagnosiscode4', models.CharField(blank=True, db_column='DiagnosisCode4', max_length=10, null=True)),
                ('diagnosisdescription5', models.CharField(blank=True, db_column='DiagnosisDescription5', max_length=255, null=True)),
                ('diagnosiscode5', models.CharField(blank=True, db_column='DiagnosisCode5', max_length=10, null=True)),
                ('diagnosisdescription6', models.CharField(blank=True, db_column='DiagnosisDescription6', max_length=255, null=True)),
                ('diagnosiscode6', models.CharField(blank=True, db_column='DiagnosisCode6', max_length=10, null=True)),
                ('investigation1', models.CharField(blank=True, db_column='Investigation1', max_length=100, null=True)),
                ('investigation2', models.CharField(blank=True, db_column='Investigation2', max_length=100, null=True)),
                ('investigation3', models.CharField(blank=True, db_column='Investigation3', max_length=100, null=True)),
                ('investigation4', models.CharField(blank=True, db_column='Investigation4', max_length=100, null=True)),
                ('investigation5', models.CharField(blank=True, db_column='Investigation5', max_length=100, null=True)),
                ('investigation6', models.CharField(blank=True, db_column='Investigation6', max_length=100, null=True)),
                ('localdiagnosis1', models.CharField(blank=True, db_column='LocalDiagnosis1', max_length=255, null=True)),
                ('localdiagnosis2', models.CharField(blank=True, db_column='LocalDiagnosis2', max_length=255, null=True)),
                ('localdiagnosis3', models.CharField(blank=True, db_column='LocalDiagnosis3', max_length=255, null=True)),
                ('localdiagnosis4', models.CharField(blank=True, db_column='LocalDiagnosis4', max_length=255, null=True)),
                ('localdiagnosis5', models.CharField(blank=True, db_column='LocalDiagnosis5', max_length=255, null=True)),
                ('localdiagnosis6', models.CharField(blank=True, db_column='LocalDiagnosis6', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('notesid', models.AutoField(db_column='NotesID', primary_key=True, serialize=False)),
                ('attendanceno', models.CharField(db_column='AttendanceNo', max_length=10)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('noteseq', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('testid', models.AutoField(db_column='TestID', primary_key=True, serialize=False)),
                ('attendanceno', models.CharField(blank=True, db_column='AttendanceNo', max_length=50, null=True)),
                ('patientid', models.CharField(db_column='PatientID', max_length=20)),
                ('datereceived', models.CharField(blank=True, max_length=27, null=True)),
                ('datebookedin', models.CharField(blank=True, max_length=27, null=True)),
                ('specimen_number', models.CharField(max_length=14)),
                ('clindetails', models.CharField(blank=True, db_column='ClinDetails', max_length=120, null=True)),
                ('set_code', models.CharField(max_length=6)),
                ('set_exp', models.CharField(blank=True, max_length=20, null=True)),
                ('specimen_taken_by', models.CharField(blank=True, max_length=20, null=True)),
                ('consultant', models.CharField(blank=True, max_length=21, null=True)),
                ('location', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'tests',
                'managed': False,
            },
        ),
    ]
