# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_code', models.CharField(db_column='Set_code', max_length=25)),
                ('set_exp', models.CharField(blank=True, db_column='Set_Exp', max_length=255, null=True)),
                ('discipline', models.CharField(blank=True, db_column='Discipline', max_length=25, null=True)),
                ('internal_recharge', models.DecimalField(blank=True, db_column='Internal_Recharge', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'Cost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gptests',
            fields=[
                ('testid', models.AutoField(db_column='TestID', primary_key=True, serialize=False)),
                ('patientid', models.CharField(db_column='PatientID', max_length=20)),
                ('datecollected', models.CharField(blank=True, max_length=27, null=True)),
                ('datereceived', models.CharField(blank=True, max_length=27, null=True)),
                ('datebookedin', models.CharField(blank=True, max_length=27, null=True)),
                ('dateauthorised', models.CharField(blank=True, max_length=27, null=True)),
                ('specimen_number', models.CharField(max_length=14)),
                ('clindetails', models.CharField(blank=True, db_column='ClinDetails', max_length=250, null=True)),
                ('set_code', models.CharField(max_length=10)),
                ('set_exp', models.CharField(blank=True, max_length=20, null=True)),
                ('specimen_taken_by', models.CharField(blank=True, max_length=20, null=True)),
                ('consultant', models.CharField(blank=True, max_length=21, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('discipline', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'GPtests',
                'managed': False,
            },
        ),
    ]
